export const SET_NEXT_MONTH = "SET_NEXT_MONTH";
export const SET_PREV_MONTH = "SET_PREV_MONTH";
export const INIT_CALENDAR = "INIT_CALENDAR";
export const SET_MONTHLY_DATA_START = "SET_MONTHLY_DATA_START";
export const SET_MONTHLY_DATA_SUCCESS = "SET_MONTHLY_DATA_SUCCESS";
export const SET_MONTHLY_DATA_FAIL = "SET_MONTHLY_DATA_FAIL"
export const SET_ALL_MONTHLY_DATA = "SET_ALL_MONTHLY_DATA"
export const SET_MONTHLY_DATE_DATA = "SET_MONTHLY_DATE_DATA"
export const SET_PREV_MONTH_DATE_DATA = "SET_PREV_MONTH_DATE_DATA"

export const OPEN_TARGET_LIST = "OPEN_TARGET_LIST"
export const CLOSE_TARGET_LIST = "CLOSE_TARGET_LIST"
export const SUBMIT_OR_UPDATE_TARGET_LIST_START = "SUBMIT_OR_UPDATE_TARGET_LIST_START"
export const SUBMIT_OR_UPDATE_TARGET_LIST_SUCCESS = "SUBMIT_OR_UPDATE_TARGET_LIST_SUCCESS"
export const SUBMIT_OR_UPDATE_TARGET_LIST_FAIL = "SUBMIT_OR_UPDATE_TARGET_LIST_FAIL"
export const RESET_SUBMISSION = "RESET_SUBMISSION"
export const SAVE_TARGET_FORM = "SAVE_TARGET_FORM";
export const SAVE_PREV_DAY_PENDING_TARGET = "SAVE_PREV_DAY_PENDING_TARGET"
export const POST_TARGET_FORM_START = "POST_TARGET_FORM_START";
export const POST_TARGET_FORM_SUCCESS = "POST_TARGET_FORM_SUCCESS"
export const POST_TARGET_FORM_FAIL = "POST_TARGET_FORM_FAIL"
export const POST_TARGET_FORM_RESET = "POST_TARGET_FORM_RESET"

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const SAVE_PERSONAL_DETAILS = "SAVE_PERSONAL_DETAILS";

export const LOGOUT = 'LOGOUT';
export const SET_ERROR_TO_NULL = "SET_ERROR_TO_NULL"

export const SET_SNACKBAR = "SET_SNACKBAR"
export const REMOVE_SNACKBAR = "REMOVE_SNACKBAR"
